# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: event123
  encoding: unicode
  database: my_app_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: event123
  encoding: unicode
  database: my_app_test
  pool: 5

production:
  adapter: postgresql
  host: localhost
  username: postgres
  password: event123
  encoding: unicode
  database: my_app_production
  pool: 5